cmdout = ['Running 1 test',...
'Changing directory from /Users/phillipbrown/chaste_build/ to /Users/phillipbrown/Chaste/.',...
'CWD now: /Users/phillipbrown/Chaste',...
'',...
'',...
' ***** TestCryptColumnMutation.hpp *****',...
'',...
'',...
'Entering TestCryptMutation',...
'DEBUG: n = 29',...
'DEBUG: n_prolif = 12',...
'DEBUG: epithelialStiffness = 58',...
'DEBUG: membraneStiffness = 216',...
'DEBUG: cellCycleTime = 15',...
'DEBUG: wPhaseLength = 9',...
'DEBUG: quiescentVolumeFraction = 0.675',...
'DEBUG: simulation_length = 400',...
'DEBUG: run_number = 1',...
'DEBUG: Mutation paramters',...
'DEBUG: mutationPosition = 1',...
'DEBUG: setPopUpDivision = 0',...
'DEBUG: msModifier = 0.7',...
'DEBUG: Simulating through transient',...
'DEBUG: Starting simulation proper',...
'DEBUG: START',...
'DEBUG: Clonal conversion',...
'DEBUG: END',...
'Passed',...
'OK!'];

try
    temp = strsplit(cmdout, 'START');
    temp1 = strsplit(temp{2}, 'END');
    temp2 = strsplit(temp1{1}, 'DEBUG: ');
catch
    error('bD:MissingBracketingFlags','Couldnt find START, END or DEBUG. Ensure the Chaste test console output is formatted correctly.');
end


data = nan;
if strcmp(temp2{2}, 'Monolayer clear') || strcmp(temp2{2}, 'Crypt clear')
    data = 0;
end
if strcmp(temp2{2}, 'Clonal conversion')
    data = 1;
end
if ~strcmp(temp2{2}, 'Monolayer clear') && ~strcmp(temp2{2}, 'Clonal conversion') && ~strcmp(temp2{2}, 'Crypt clear')
    error('bD:MissingData','Console output format doesnt match expected format.');
end

