sbatch genericCheckCentroids.sh MouseColonAsc_centroids.txt MouseColonAsc
sbatch genericCheckCentroids.sh MouseColonDesc_centroids.txt MouseColonDesc
sbatch genericCheckCentroids.sh MouseColonCaecum_centroids.txt MouseColonCaecum
sbatch genericCheckCentroids.sh RatColonCaecum_centroids.txt RatColonCaecum